name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # SSH setup
    - name: Setup SSH keys
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > deploy_key.pem
        chmod 600 deploy_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    # Transfer frontend source and .env file to production
    - name: Transfer frontend source to production
      run: |
        rsync -avz --exclude='node_modules' --exclude='.env' --no-times --no-perms -e "ssh -i deploy_key.pem" frontend/ ${{ secrets.USER }}@${{ secrets.HOST }}:/home/githubactions/BacklogApp/frontend/

    # Create .env file, build frontend, and deploy to production server
    - name: Build and deploy frontend on production server
      run: |
        ssh -i deploy_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} '
        cd /home/githubactions/BacklogApp/frontend/ && 
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env &&
        echo "REACT_APP_URL=${{ secrets.REACT_APP_URL }}" >> .env &&
        echo "REACT_APP_BACKLOG_CLIENTID=${{ secrets.REACT_APP_BACKLOG_CLIENTID }}" >> .env &&
        echo "REACT_APP_BACKLOG_REDIRECT_URI=${{ secrets.REACT_APP_BACKLOG_REDIRECT_URI }}" >> .env &&
        npm install && npm run build &&
        rm -rf /var/www/backlog.daichisakai.net/* &&
        cp -r build/* /var/www/backlog.daichisakai.net/'

    # Backend setup and build
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Create .env file for backend
      run: |
        echo "DB_INFO=$(echo '${{ secrets.DB_INFO }}' | sed 's/\\/\\\\/g')" >> .env
        echo "API_URL=${{ secrets.API_URL }}" >> backend/.env
        echo "SECRETKEY1=${{ secrets.SECRETKEY1 }}" >> backend/.env
        echo "SECRETKEY2=${{ secrets.SECRETKEY2 }}" >> backend/.env
        echo "SECRETKEY3=${{ secrets.SECRETKEY3 }}" >> backend/.env
        echo "BACKLOG_CLIENT_ID=${{ secrets.BACKLOG_CLIENT_ID }}" >> backend/.env
        echo "BACKLOG_CLIENT_SECRET=${{ secrets.BACKLOG_CLIENT_SECRET }}" >> backend/.env
        echo "BACKLOG_REDIRECT_URI=${{ secrets.BACKLOG_REDIRECT_URI }}" >> backend/.env

    - name: Build backend
      run: |
        cd backend
        go build -o build main.go

    # Transfer .env file to production server
    - name: Transfer .env file to production backend
      run: |
        scp -i deploy_key.pem backend/.env ${{ secrets.USER }}@${{ secrets.HOST }}:/home/githubactions/BacklogApp/backend/

    # Application stop
    - name: Stop the backend application
      run: |
        ssh -i deploy_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} '/home/githubactions/.npm-global/bin/pm2 stop BacklogApp'

    # Backend deployment
    - name: Transfer backend build to production
      run: |
        scp -i deploy_key.pem -r backend/build ${{ secrets.USER }}@${{ secrets.HOST }}:/home/githubactions/BacklogApp/backend/build

    # Application start
    - name: Restart the backend application
      run: |
        ssh -i deploy_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} 'cd /home/githubactions/BacklogApp/backend && /home/githubactions/.npm-global/bin/pm2 restart BacklogApp'
