name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Frontend setup and build
    - name: Setup Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: cd frontend && npm ci

    - name: Create .env file for frontend
      run: |
        echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> frontend/.env

    - name: Build frontend
      env:
        CI: false
      run: cd frontend && npm run build

    # SSH setup
    - name: Setup SSH keys
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > deploy_key.pem
        chmod 600 deploy_key.pem
        mkdir -p ~/.ssh
        ssh-keyscan ${{ secrets.HOST }} >> ~/.ssh/known_hosts

    # Frontend deployment
    - name: Transfer frontend build to production
      run: |
        rsync -avz --exclude='node_modules' --no-times --no-perms -e "ssh -i deploy_key.pem" frontend/build/ ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/backlog.daichisakai.net/

    # Backend setup and build
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.6'

    - name: Create .env file for backend
      run: |
        echo "DB_INFO=${{ secrets.DB_INFO }}" >> backend/.env
        echo "API_URL=${{ secrets.API_URL }}" >> backend/.env
        echo "SECRETKEY1=${{ secrets.SECRETKEY1 }}" >> backend/.env
        echo "SECRETKEY2=${{ secrets.SECRETKEY2 }}" >> backend/.env

    - name: Build backend
      run: |
        cd backend
        go build -o build main.go

    # Application stop
    - name: Stop the backend application
      run: |
        ssh -i deploy_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} '/home/githubactions/.npm-global/bin/pm2 stop BacklogApp'

    # Backend deployment
    - name: Transfer backend build to production
      run: |
        scp -i deploy_key.pem -r backend/build ${{ secrets.USER }}@${{ secrets.HOST }}:/home/githubactions/BacklogApp/backend/build

    # Application start
    - name: Restart the backend application
      run: |
        ssh -i deploy_key.pem ${{ secrets.USER }}@${{ secrets.HOST }} 'cd /home/githubactions/BacklogApp/backend && /home/githubactions/.npm-global/bin/pm2 restart BacklogApp'
